### ISSUE TITLE
Add meaningful error handling for wrong API methods

### ISSUE THREAD

**Issue by evra** [maximepvrt/angular-google-gapi#13]
Hi, 

When I'm calling a not existing method I'm getting the following error message in console

``` javascript
TypeError: api is not a function
    at runGapi (http://localhost:9000/bower_components/angular-google-gapi/angular-google-gapi.js:309:13)
    at execute (http://localhost:9000/bower_components/angular-google-gapi/angular-google-gapi.js:321:17)
    at Object.execute (http://localhost:9000/bower_components/angular-google-gapi/angular-google-gapi.js:340:28)
    at Scope.$scope.addNewProfile (http://localhost:9000/scripts/controllers/userprofiles.js:27:8)
    at $parseFunctionCall (http://localhost:9000/bower_components/angular-scenario/angular-scenario.js:21596:18)
    at ngEventDirectives.(anonymous function).compile.element.on.callback (http://localhost:9000/bower_components/angular-scenario/angular-scenario.js:30758:17)
    at Scope.$get.Scope.$eval (http://localhost:9000/bower_components/angular-scenario/angular-scenario.js:23658:28)
    at Scope.$get.Scope.$apply (http://localhost:9000/bower_components/angular-scenario/angular-scenario.js:23757:23)
    at HTMLFormElement.<anonymous> (http://localhost:9000/bower_components/angular-scenario/angular-scenario.js:30763:23)
    at HTMLFormElement.jQuery.event.dispatch (http://localhost:9000/bower_components/jquery/dist/jquery.js:4435:9)
```

It would be really helpful to get something like "Method xyz is not found in API 'myApi'" instead.

Thank you.

**Comment by vacarsu** [comment]
I think displaying meaningful error messages would be a highly involved task as you would have to keep a list of all the possibilities in code. As of how right now, I believe the wrapper takes whatever you pass it and concatenates a query. It doesn't know whether the api exists or not before passing it to the Gapi client. I could be wrong however.

**Comment by maximepvrt** [comment]
@vacarsu It's exactly that !
